Repository pc-xpress/petyshop-api, pull requests merged in 2024-06, with the labels that each got.

#3 Create user login
  app/Http/Requests/Api/v1/Auth/StoreAuthRequest.php
Labels: enhancement

#5 #4 Create testing for login user
  tests/Feature/Api/v1/Auth/LoginTest.php
Labels: enhancement, new, Testing

#9 testing
  tests/Feature/Api/v1/Auth/LoginTest.php
Labels: duplicate

#12 #8 Create test to user register
  app/Http/Controllers/Api/v1/Register/RegisterController.php
  app/Http/Requests/Api/v1/User/CreateUserRequest.php
  app/Http/Resources/Api/v1/Auth/AuthResource.php
  app/Models/User.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/seeders/UserSeeder.php
  routes/api.php
  tests/Feature/Api/v1/Auth/UserRegisterTest.php
  tests/TestCase.php
Labels: enhancement, new, Testing

#13 Refactory user register test
  app/Http/Controllers/Api/v1/Register/RegisterController.php
  database/factories/UserFactory.php
  tests/Feature/Api/v1/Auth/LoginTest.php
  tests/Feature/Api/v1/Auth/UserRegisterTest.php
Labels: Testing, refacty

#14 feat(API): Update user data with their test
  .gitignore
  app/Http/Controllers/Api/v1/Profile/ProfileController.php
  app/Http/Controllers/Api/v1/Register/RegisterController.php
  app/Http/Requests/Api/v1/User/UpdateUserRequest.php
  phpunit.xml
  routes/api.php
  tests/Feature/Api/v1/Auth/UpdateUserDataTest.php
  tests/Feature/ExampleTest.php
  tests/TestCase.php
Labels: enhancement, Testing

#15 refactor(api): :fire: Refactoring update function
  app/Http/Controllers/Api/v1/Profile/ProfileController.php
Labels: Testing, refacty

#17 fix(api): 🔥 Restructuring the api authorization folders
  app/Http/Controllers/Api/v1/Auth/LoginController.php
  app/Http/Controllers/Api/v1/Auth/ProfileController.php
  app/Http/Controllers/Api/v1/Auth/RegisterController.php
  app/Http/Controllers/Api/v1/LoginController.php
  routes/api.php
Labels: refacty

#18 Refactor/api
  app/Classes/ApiResponseHelper.php
  app/Http/Controllers/Api/v1/Auth/LoginController.php
  app/Http/Controllers/Api/v1/Auth/ProfileController.php
  app/Http/Controllers/Api/v1/Auth/RegisterController.php
  app/Http/Controllers/Api/v1/Auth/UpdatePasswordController.php
  app/Rules/CheckPasswordRule.php
Labels: refacty

#19 Feature/creat reset password method
  app/Http/Controllers/Api/v1/Auth/ResetPasswordController.php
  app/Models/User.php
  app/Notifications/ResetPasswordNotification.php
  routes/api.php
Labels: enhancement

#20 test(Api): :white_check_mark: create password reset function test
  app/Http/Controllers/Api/v1/Auth/ResetPasswordController.php
  app/Models/User.php
  routes/api.php
  tests/Feature/Api/v1/Auth/ResetPasswordTest.php
Labels: Testing

#21 fix(Api): :art: Forse Json response middleware to handler the headers…
  app/Http/Middleware/ForseJsonResponseMiddleware.php
  app/Notifications/ResetPasswordNotification.php
  bootstrap/app.php
Labels: enhancement
